### ISSUE TITLE
Extremely low Preformance

### ISSUE THREAD

**Issue by Astra060** [yurisuika/Zehn#10]
Hello. The skin looks fantastic, but there are performance issues. I installed the skin today so I don't know if this is because of the steam version. But Everything seems to be running 5x slower.

If I get my pointer on a button, it needs to wait a few seconds to respond for example, this includes clicking it as well.

**Comment by yurisuika** [comment]
I have noticed it is a little slower than stock Steam. There is a config option to adjust the blur radius (as background blur on top of translucent backgrounds is heavily used to emulate MDL2).

Beyond that, I do not know enough about webdev to know why the skin would be slow asides from being quite large.

**Comment by pbanj** [comment]
@Astra060 what gpu do you have? intel arc cards lack directx 9 support and instead they emulate it(or something along those lines). It results in poor perf from anything directx 9.

**Comment by yurisuika** [comment]
I am pretty sure this was fixed during the remapping, some of the CSS entries were malformed and it was probably causing the lag.
