### ISSUE TITLE
Unnable to use navigation buttons at the top of the screen

### ISSUE THREAD

**Issue by TheCorbs09** [yurisuika/Zehn#11]
The newest update doesn't fix an issue people have been having since the 15th of last month, disabling JavaScript makes the navigation buttons work again but some of the buttons disappear and the theme doesn't look right.

**Comment by yurisuika** [comment]
Are you using the Steam Beta?

**Comment by yurisuika** [comment]
If you can post some images to show what is wrong, it will help to convey the issue. I don't know who these people are who have had this issue for a month, this is the first I am hearing of this.

**Comment by TheCorbs09** [comment]
No im not using steam beta and I think this has been stated before but steam changed its class names and I think that was the problem cause it seems to be working now

**Comment by yurisuika** [comment]
There is a beta branch for steam beta, but as far as I can tell those class name changes are not out yet for stable.

![image](https://github.com/yurisuika/Zehn/assets/7410303/71b340d0-0da4-43d1-bf59-d788728e5e2f)

![image](https://github.com/yurisuika/Zehn/assets/7410303/3f49ee1d-d7b4-42da-a8b7-3123ddf43cb9)

You can see the skin that is on the master branch works fine without Beta, broken with Beta.

![image](https://github.com/yurisuika/Zehn/assets/7410303/8692400f-a5dd-4073-bc6a-9e1552e12b0d)

Still not changed classes on stable branch.

Are you getting the changed class names on the stable branch? If so, for some reason Steam must be giving differential distribution of this update. I cannot force my client to get any such update for stable.

**Comment by yurisuika** [comment]
Since you stated it works, I am closing the issue.
