### ISSUE TITLE
Can we get non rounded edges option again?

### ISSUE THREAD

**Issue by PlainDoll17** [yurisuika/Zehn#18]
Love this skin, been using it since it's inception, but i do miss non rounded edges option

Oh, and while im at it, what about settings embedded into millennium so we dont have to edit config and just change skin options in millennium itself? 

Thank you! <3

**Comment by yurisuika** [comment]
Well before when that was around, avatars were being rounded via a simple border radius (and legacy design of the status being the border color). But now they are actually masked off with individual masks for different status icons.

I can make a new set of masks for square versions (I think some things are still using legacy border radii cuz they don't have any statuses)... As far as the config goes, that wouldn't look pretty for a config, but I will look into how Millennium has embedded settings. I do not know if SFP has such a feature, however. Ideally I'd like to add my own settings page on the Steam settings if possible. I assume if you use the skin installed via Millennium, it will reset the config.css every time there is an update, which is not ideal. I figure this is why they have embedded config options. Nonetheless, I will look into supporting it!

**Comment by yurisuika** [comment]
I've come up with a solution that is injector agnostic. It uses JS and detects whether a config option is `square` or `round`. Well, it detects if it is `square`, else it uses round. I still have to incorporate other avatars like groups, but normal user avatars are done. This is only out on the beta branch for the recording beta.
