### ISSUE TITLE
Steam Overlay/Settings Icons

### ISSUE THREAD

**Issue by dyerbetes** [yurisuika/Zehn#21]
Hello, really enjoying the theme! When using the Shift+Tab overlay the Friends, Web Browser, Controller Settings and Game Recording buttons seem to have the icons in the wrong order/placement. There may seem to also be some issues in the client settings with icons as well as some are completely missing. Hopefully this is helpful in some capacity. 
(Images for reference)

![icons](https://github.com/user-attachments/assets/06411a58-9e0c-4542-89cb-4f84672d8be4)
![icons2](https://github.com/user-attachments/assets/3d4d50c9-d66e-4c53-82b9-6023bbb9f378)

**Comment by yurisuika** [comment]
You are on Steam Beta branch, it breaks a lot.

**Comment by yurisuika** [comment]
Work for the Recording Beta is now available on the beta branch. This is not compatible with the current stable release.
