### ISSUE TITLE
new class names conversion

### ISSUE THREAD

**Issue by ricewind012** [yurisuika/Zehn#24]
i see in the "beta" branch you are trying to convert to new classes, but i made a script for exactly this purpose in this repo: https://github.com/ricewind012/steam-theming-utils
just install node.js and in your theme directory run this:
```
npm i steam-theming-utils
npx steam-theming-utils replace_old_classes
```
it also has the tools to use readable class names instead ([example](https://github.com/ricewind012/more-advanced-theme-template)), but it's 1 step more for writing css, so it may not be that convenient for you

**Comment by yurisuika** [comment]
Ah thank you! I had just finished making a map for cssmapper yesterday the best I could. Seems yours recognizes 3153 changes, which means I only missed out on around 100. Was fun manually going through about 150k lines haha.

Those sound like some pretty nifty features, I'll check it out!
