### ISSUE TITLE
some components are not rendered

### ISSUE THREAD

**Issue by proxyerium** [yurisuika/Zehn#26]
![image](https://github.com/user-attachments/assets/a6da3682-48e4-4d53-98f7-dd418004b35d)

![image](https://github.com/user-attachments/assets/bbdb940b-7602-4dbe-b9d5-d11747275eb9)

![image](https://github.com/user-attachments/assets/02131666-0408-456c-9a99-eb2c70908a91)

### my system info

Steam Version:  1726604483
Steam Client Build Date:  Wed, Sep 18 05:03 UTC -08:00
Steam Web Build Date:  Tue, Sep 17 07:12 UTC -08:00
Steam API Version:  SteamClient021

Edition:	Windows 10 IoT Enterprise LTSC
Version:	21H2
OS build:	19044.5011
Experience:	Windows Feature Experience Pack 1000.19060.1000.0

Patcher: Millennium v2.12.4

**Comment by yurisuika** [comment]
If you're on beta branch you have to use the beta build.

**Comment by yurisuika** [comment]
Actually it seems recording beta is still in beta but they pushed everything else out to stable? well it seems compatible so I'll merge the beta branch

**Comment by proxyerium** [comment]
> If you're on beta branch you have to use the beta build.

yes i think these problems occured within the last stable build [2024.9.26](https://github.com/yurisuika/Zehn/releases/tag/2024.9.26), is this the right version?

i've updated to new version released yesterday, while the above problems have been solved, new problems come.

![image](https://github.com/user-attachments/assets/d8e0bd48-559b-48b2-98cc-fbbb77c53cac "missing icons")

![image](https://github.com/user-attachments/assets/4be8d248-390c-48ff-9fd5-0e8f44249557 "messy sidebar")

![image](https://github.com/user-attachments/assets/959f1636-4c0f-40f8-816c-afdedd86d135 "where's my avatar")

**Comment by yurisuika** [comment]
This might have been something that broke in the git merge. Millennium does not support this Steam build yet so it isn't easy to test.

**Comment by yurisuika** [comment]
Okay I think that is fixed?

![image](https://github.com/user-attachments/assets/b3ca5b4b-e8a4-44a9-8d58-7f76621d37d0)

Pretty sure it was from manually merging some conflicts on git, must have messed that up.

**Comment by proxyerium** [comment]
yes, now they look fine <3

**Comment by yurisuika** [comment]
Well it turns out I was using an old version of Millennium and it works quite differently now. I'll be working some of these changes into Zehn soon.
