### ISSUE TITLE
Refresh button for updates missing

### ISSUE THREAD

**Issue by tdr1995** [yurisuika/Zehn#28]
![image](https://github.com/user-attachments/assets/7a2548bb-00cb-4283-b89f-a6b0493dffac)

Wasn't sure if you were aware, but the refresh button for Theme updates is missing. Mine doesn't appear unless I refresh, so switching to another theme to update is usually necessary.

**Comment by yurisuika** [comment]
Thanks, I thought I had noticed one before. It is still right next to the title but its just transparent.

**Comment by yurisuika** [comment]
Ah forgot to close this but it is fixed!
