### ISSUE TITLE
UI Issue - Favorites

### ISSUE THREAD

**Issue by bbirchman** [yurisuika/Zehn#29]
Hi, first off I love your skin! Big thanks for putting this together. 

Basic System Specs:
Kubuntu (Ubuntu 24.04 based)
Graphics Platform: Wayland

I am having some trouble with the UI. Certain titles (Enshrouded, Overwatch 2, No Man's Sky) are wrapping to the next line. My main guess is because of the "Update Required" text pushing it too long next to the icons.

If I were to give my best guess, you may need to add a text: nowrap to that CSS, wherever it may be.
I could be completely off - I'm not sure how you implemented it! 

Here's a screenshot: 
![zehn-bug](https://github.com/user-attachments/assets/9c21005d-e49b-4400-8c41-d96c483d213f)

Cheers, let me know if you ever want any help with contributions, or have any TODOs to pass off :)

**Comment by bbirchman** [comment]
Update - a temporary fix is to disable icons. Then the text fits without wrapping weirdly.

**Comment by yurisuika** [comment]
I broke this earlier when reworking the list to trim overflows into ellipses, forgot to check with icons enabled. The fix will be out soon.
