### ISSUE TITLE
Games with pending updates in library has wierd text formatting

### ISSUE THREAD

**Issue by legofanlovessayori** [yurisuika/Zehn#30]
99% sure this is localization related again, same as #22. All games with currently downloading or pending updates put the update status into a seperate line irregardless how wide the library sidebar is or not (and in turn makes that the button for said game overlaps other ui elements).

https://github.com/user-attachments/assets/62e7372c-db1e-4d30-9a63-dbe0226cabeb

**Comment by yurisuika** [comment]
![image](https://github.com/user-attachments/assets/b05e2744-0c0c-4382-a4ee-a438ebfebfc4)
Should be fixed now, the last time it was only in the scope of ones with cloud error. These obfuscated class names don't help with that much haha.
