### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by ShadowMonster99** [yurisuika/Zehn#9]
prepare for beta updates. Steam has changed all class names inside the client on the beta branch; It will soon become public. you will need to use this tool to update your theme when the beta version because public.

https://github.com/SteamClientHomebrew/ClassMapper

**Comment by yurisuika** [comment]
Holy shit I wish I had seen this sooner, I haven't been logged on for almost two months. I was manually converting stuff with the beta open in a VM. :(

Thank you immensely!

**Comment by ShadowMonster99** [comment]
Yeah, you should check discord more often or join the server. I've also removed your theme in the meantime considering lots of people have reported it broken.

**Comment by yurisuika** [comment]
Are you saying this change is out of beta now? If so, I have yet to get the update and cannot force it by changing between branches.

If you are referencing #11, that report is the only suggestion I have had that anything is broken.

**Comment by ShadowMonster99** [comment]
No, the updates aren't live. Many people reported banner ads or something on your theme and it was getting a little frustrating having to deal with it when you were no where to be found, so we took your theme down. Many others have also reported bad performance like latency issues.

No worries though, we totally get not everyone has the time to maintain a theme. 

Hope this helps 
Cheers!

**Comment by yurisuika** [comment]
It wasn't an ad, it was a warning for users about the upcoming changes with the class names and provided details on they can bypass the update until the skin was remapped. I wasn't aware about your remapper and was manually converting all of the class names, which was not only not fun but was a very extensive process to undertake manually, as roughly estimated by the amount of curly brackets in the skin to being 5000 declarations.

I am sorry that they are troubling you with it, as they should be reporting their bugs here.
